import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { generateSigningKeyPair, serializeMandate, signMandate, snapshotHash, type Mandate, type Snapshot } from "@oathline/core";
import { parseReceiptLines, verifyChain } from "@oathline/receipts";
import { postToolUse, preToolUse, sessionStart } from "../src/index.js";

const repoRoot = path.resolve("../.."); let home = ""; let environment: NodeJS.ProcessEnv;
const unsigned: Mandate = { meta:{name:"runtime-test",expires_at:"2026-09-08T22:00:00Z",timezone:"UTC"},scope:{products:["SPOT"],symbols:["BNBUSDT"],sides:["BUY","SELL"],order_types:["MARKET","LIMIT"]},budget:{max_order_usdt:"15",max_daily_gross_usdt:"40",max_position_usdt:"50"},rate:{max_orders_per_day:3,cooldown_seconds:300},risk:{max_session_drawdown_pct:"2"},market:{max_spread_bps:"20"},state:{max_age_seconds:30},escalation:{stale_state:"ASK",unknown_tool:"ASK",hard_violation:"DENY"},signature:null };
function state(): Snapshot { const body: Omit<Snapshot,"hash">={snapshotVersion:"1.0",source:"binance-agent-os",client:"codex",clientVersion:"0.153.3",capturedAt:new Date(Date.now()-1000).toISOString(),toolUseIds:["read-1"],account:{equityUsdt:"40",balances:null,positions:null},market:{BNBUSDT:{bid:"718.40",ask:"718.60",referencePrice:"718.50",spreadBps:"2.783576896311760612"}},sessionOpenEquityUsdt:"40"}; return {...body,hash:snapshotHash(body)}; }
function pre(quoteOrderQty: number): string { return JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.newOrder",arguments:{symbol:"BNBUSDT",side:"SELL",type:"MARKET",quoteOrderQty}},tool_use_id:`write-${quoteOrderQty}`}); }
beforeEach(async()=>{ home=await mkdtemp(path.join(tmpdir(),"oathline-runtime-")); environment={...process.env,OATHLINE_HOME:home}; const keys=generateSigningKeyPair(); await writeFile(path.join(home,"oathline.toml"),serializeMandate(signMandate(unsigned,keys.privateKey,keys.publicKey))); await writeFile(path.join(home,"state.json"),JSON.stringify(state())); });

describe("Codex runtime",()=>{
  it("denies an out-of-mandate write and appends proposal plus ruling",async()=>{ const output=JSON.parse(await preToolUse(pre(83.4),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("83.40 USDT exceeds the 15.00 USDT permitted per order"); const entries=parseReceiptLines(await readFile(path.join(home,"receipts.jsonl"),"utf8")); expect(entries.map((entry)=>entry.kind)).toEqual(["proposal","ruling"]); expect(await verifyChain(path.join(home,"receipts.jsonl"))).toMatchObject({valid:true,entries:2}); });
  it("allows a fully observed inside-mandate write with factual context",async()=>{ const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision?:string;additionalContext:string}}; expect(output.hookSpecificOutput.permissionDecision).toBeUndefined(); expect(output.hookSpecificOutput.additionalContext).toMatch(/^Oathline ruling for this order\./); });
  it("fails closed when state is missing",async()=>{ environment.OATHLINE_STATE=path.join(home,"missing-state.json"); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("NEEDS APPROVAL"); });
  it("fails closed with a clear startup error when the mandate is missing",async()=>{ environment.OATHLINE_MANDATE=path.join(home,"missing-mandate.toml"); const before=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(before.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); const started=await sessionStart(repoRoot,environment); expect(started.stderr).toContain(`Oathline is NOT active: mandate not found at ${environment.OATHLINE_MANDATE}`); });
  it("reports an expired mandate as inactive and withholds writes",async()=>{ const keys=generateSigningKeyPair(); const expired={...unsigned,meta:{...unsigned.meta,expires_at:"2026-09-04T00:00:00Z"}}; await writeFile(path.join(home,"oathline.toml"),serializeMandate(signMandate(expired,keys.privateKey,keys.publicKey))); const started=await sessionStart(repoRoot,environment); expect(started.stderr).toContain("Oathline is NOT active: mandate expired at 2026-09-04T00:00:00Z"); const before=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(before.hookSpecificOutput.permissionDecision).toBe("deny"); expect(before.hookSpecificOutput.permissionDecisionReason).toContain("OUTSIDE MANDATE"); });
  it("fails closed when the receipt chain is corrupt",async()=>{ await writeFile(path.join(home,"receipts.jsonl"),'{"seq":1,"broken":true}\n'); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); });
  it("fails closed on malformed JSON and malformed hook shapes",async()=>{ for (const raw of ["{",JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:null})]) { const output=JSON.parse(await preToolUse(raw,repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); } });
  it("denies an unobserved dispatcher operation",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.futureMysteryOrder",arguments:{symbol:"BNBUSDT",side:"SELL",type:"MARKET",quoteOrderQty:1}},tool_use_id:"unknown-write"}); const output=JSON.parse(await preToolUse(raw,repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); });
  it("observes a wallet balance response into state",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"wallet.queryUserWalletBalance",arguments:{quoteAsset:"USDT"}},tool_response:{content:[{type:"text",text:'[{"activate":true,"balance":"40","walletName":"Spot"}]'}],isError:false},tool_use_id:"balance-read"}); await postToolUse(raw,repoRoot,environment); const observed=JSON.parse(await readFile(path.join(home,"state.json"),"utf8")) as Snapshot; expect(observed.account.equityUsdt).toBe("40"); expect(observed.toolUseIds).toContain("balance-read"); });
  it("records Binance order id from a write response",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.newOrder",arguments:{symbol:"BNBUSDT",side:"BUY",type:"MARKET",quoteOrderQty:10}},tool_response:{content:[{type:"text",text:'{"symbol":"BNBUSDT","orderId":987654,"status":"FILLED"}'}],isError:false},tool_use_id:"executed-write"}); await postToolUse(raw,repoRoot,environment); const entries=parseReceiptLines(await readFile(path.join(home,"receipts.jsonl"),"utf8")); expect(entries[0]).toMatchObject({kind:"execution",toolUseId:"executed-write",orderId:"987654",isError:false}); });
});
