import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { generateSigningKeyPair, serializeMandate, signMandate, snapshotHash, type Mandate, type Snapshot } from "@oathline/core";
import { appendReceipt, parseReceiptLines, verifyChain } from "@oathline/receipts";
import { postToolUse, preToolUse, sessionStart } from "../src/index.js";

const repoRoot = path.resolve("../.."); let home = ""; let environment: NodeJS.ProcessEnv;
const unsigned: Mandate = { meta:{name:"runtime-test",expires_at:"2026-09-08T22:00:00Z",timezone:"UTC"},scope:{products:["SPOT"],symbols:["BNBUSDT"],sides:["BUY","SELL"],order_types:["MARKET","LIMIT"]},budget:{max_order_usdt:"15",max_daily_gross_usdt:"40",max_position_usdt:null},rate:{max_orders_per_day:3,cooldown_seconds:300},risk:{max_session_drawdown_pct:"2"},market:{max_spread_bps:"20"},state:{max_age_seconds:30},escalation:{stale_state:"ASK",unknown_tool:"ASK",hard_violation:"DENY"},signature:null };
function state(): Snapshot { const body: Omit<Snapshot,"hash">={snapshotVersion:"1.0",source:"binance-agent-os",client:"codex",clientVersion:"0.153.3",capturedAt:new Date(Date.now()-1000).toISOString(),toolUseIds:["read-1"],account:{equityUsdt:"40",balances:null,positions:null},market:{BNBUSDT:{bid:"718.40",ask:"718.60",referencePrice:"718.50",spreadBps:"2.783576896311760612"}},sessionOpenEquityUsdt:"40"}; return {...body,hash:snapshotHash(body)}; }
function pre(quoteOrderQty: number): string { return JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.newOrder",arguments:{symbol:"BNBUSDT",side:"SELL",type:"MARKET",quoteOrderQty}},tool_use_id:`write-${quoteOrderQty}`}); }
function hook(toolName: string, args: Record<string, unknown>, toolUseId = "write-custom"): string { return JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName,arguments:args},tool_use_id:toolUseId}); }
async function installMandate(change: (mandate: Mandate) => void): Promise<void> { const next=structuredClone(unsigned); change(next); const keys=generateSigningKeyPair(); await writeFile(path.join(home,"oathline.toml"),serializeMandate(signMandate(next,keys.privateKey,keys.publicKey))); }
beforeEach(async()=>{ home=await mkdtemp(path.join(tmpdir(),"oathline-runtime-")); environment={...process.env,OATHLINE_HOME:home}; const keys=generateSigningKeyPair(); await writeFile(path.join(home,"oathline.toml"),serializeMandate(signMandate(unsigned,keys.privateKey,keys.publicKey))); await writeFile(path.join(home,"state.json"),JSON.stringify(state())); });

describe("Codex runtime",()=>{
  it("denies an out-of-mandate write and appends proposal plus ruling",async()=>{ const output=JSON.parse(await preToolUse(pre(83.4),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("83.40 USDT exceeds the 15.00 USDT permitted per order"); const entries=parseReceiptLines(await readFile(path.join(home,"receipts.jsonl"),"utf8")); expect(entries.map((entry)=>entry.kind)).toEqual(["proposal","ruling"]); expect(await verifyChain(path.join(home,"receipts.jsonl"))).toMatchObject({valid:true,entries:2}); });
  it("allows a fully observed inside-mandate write with factual context",async()=>{ const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision?:string;additionalContext:string}}; expect(output.hookSpecificOutput.permissionDecision).toBeUndefined(); expect(output.hookSpecificOutput.additionalContext).toMatch(/^Oathline ruling for this order\./); });
  it("fails closed when state is missing",async()=>{ environment.OATHLINE_STATE=path.join(home,"missing-state.json"); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("NEEDS APPROVAL"); });
  it("fails closed with a clear startup error when the mandate is missing",async()=>{ environment.OATHLINE_MANDATE=path.join(home,"missing-mandate.toml"); const before=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(before.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); const started=await sessionStart(repoRoot,environment); expect(started.stderr).toContain(`Oathline is NOT active: mandate not found at ${environment.OATHLINE_MANDATE}`); });
  it("reports an expired mandate as inactive and withholds writes",async()=>{ const keys=generateSigningKeyPair(); const expired={...unsigned,meta:{...unsigned.meta,expires_at:"2026-09-04T00:00:00Z"}}; await writeFile(path.join(home,"oathline.toml"),serializeMandate(signMandate(expired,keys.privateKey,keys.publicKey))); const started=await sessionStart(repoRoot,environment); expect(started.stderr).toContain("Oathline is NOT active: mandate expired at 2026-09-04T00:00:00Z"); const before=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(before.hookSpecificOutput.permissionDecision).toBe("deny"); expect(before.hookSpecificOutput.permissionDecisionReason).toContain("OUTSIDE MANDATE"); });
  it("fails closed when the receipt chain is corrupt",async()=>{ await writeFile(path.join(home,"receipts.jsonl"),'{"seq":1,"broken":true}\n'); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); });
  it("fails closed on malformed JSON and malformed hook shapes",async()=>{ for (const raw of ["{",JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:null})]) { const output=JSON.parse(await preToolUse(raw,repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput).toEqual({hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:"Oathline could not render a ruling — order withheld"}); } });
  it("denies an unobserved dispatcher operation",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.futureMysteryOrder",arguments:{symbol:"BNBUSDT",side:"SELL",type:"MARKET",quoteOrderQty:1}},tool_use_id:"unknown-write"}); const output=JSON.parse(await preToolUse(raw,repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); });
  it("denies SELL under a signed BUY-only mandate",async()=>{ await installMandate((value)=>{ value.scope.sides=["BUY"]; }); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("SELL is not in [BUY]"); });
  it("denies MARKET under a signed LIMIT-only mandate",async()=>{ await installMandate((value)=>{ value.scope.order_types=["LIMIT"]; }); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("MARKET is not in [LIMIT]"); });
  it("denies an order inside the signed cooldown",async()=>{ const now=new Date(); const previous=new Date(now.getTime()-40_000).toISOString(); await appendReceipt(path.join(home,"receipts.jsonl"),{ts:previous,kind:"proposal",toolUseId:"previous-write",notionalUsdt:"5"}); await appendReceipt(path.join(home,"receipts.jsonl"),{ts:previous,kind:"execution",toolUseId:"previous-write",orderId:"prior",isError:false}); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("since the last successful order is below the 300s cooldown"); });
  it("withholds stale state alone as NEEDS_APPROVAL",async()=>{ const stale=state(); stale.capturedAt=new Date(Date.now()-94_200).toISOString(); const {hash:_hash,...body}=stale; stale.hash=snapshotHash(body); await writeFile(path.join(home,"state.json"),JSON.stringify(stale)); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("NEEDS APPROVAL"); });
  it("keeps a known hard max-order breach OUTSIDE_MANDATE when state is stale",async()=>{ const stale=state(); stale.capturedAt=new Date(Date.now()-94_200).toISOString(); const {hash:_hash,...body}=stale; stale.hash=snapshotHash(body); await writeFile(path.join(home,"state.json"),JSON.stringify(stale)); const output=JSON.parse(await preToolUse(pre(83.4),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("OUTSIDE MANDATE"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("83.40 USDT exceeds the 15.00 USDT permitted per order"); });
  it("withholds a mutation-shaped unaudited operation",async()=>{ const output=JSON.parse(await preToolUse(hook("futures_coin.changeInitialLeverage",{symbol:"BNBUSDT",leverage:20}),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); });
  it("withholds a mandate with an invalid signature",async()=>{ const keys=generateSigningKeyPair(); const signed=signMandate(structuredClone(unsigned),keys.privateKey,keys.publicKey); signed.scope.sides=["BUY"]; await writeFile(path.join(home,"oathline.toml"),serializeMandate(signed)); const output=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{permissionDecision:string;permissionDecisionReason:string}}; expect(output.hookSpecificOutput.permissionDecision).toBe("deny"); expect(output.hookSpecificOutput.permissionDecisionReason).toContain("OUTSIDE MANDATE"); });
  it("uses ENFORCED only for the personally observed client and version marker",async()=>{ await writeFile(path.join(home,"enforcement.json"),JSON.stringify({honored:true,client:"Codex CLI",clientVersion:"0.153.3"})); const enforced=JSON.parse(await preToolUse(pre(10),repoRoot,environment)) as {hookSpecificOutput:{additionalContext:string}}; expect(enforced.hookSpecificOutput.additionalContext).toContain("mode       ENFORCED"); const secondHome=await mkdtemp(path.join(tmpdir(),"oathline-runtime-version-")); const secondEnvironment={...environment,OATHLINE_HOME:secondHome}; await writeFile(path.join(secondHome,"oathline.toml"),await readFile(path.join(home,"oathline.toml"))); await writeFile(path.join(secondHome,"state.json"),JSON.stringify(state())); await writeFile(path.join(secondHome,"enforcement.json"),JSON.stringify({honored:true,client:"Codex CLI",clientVersion:"0.154.0"})); const advisory=JSON.parse(await preToolUse(pre(10),repoRoot,secondEnvironment)) as {hookSpecificOutput:{additionalContext:string}}; expect(advisory.hookSpecificOutput.additionalContext).toContain("mode       ADVISORY"); });
  it("observes a wallet balance response into state",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"wallet.queryUserWalletBalance",arguments:{quoteAsset:"USDT"}},tool_response:{content:[{type:"text",text:'[{"activate":true,"balance":"40","walletName":"Spot"}]'}],isError:false},tool_use_id:"balance-read"}); await postToolUse(raw,repoRoot,environment); const observed=JSON.parse(await readFile(path.join(home,"state.json"),"utf8")) as Snapshot; expect(observed.account.equityUsdt).toBe("40"); expect(observed.toolUseIds).toContain("balance-read"); });
  it("records Binance order id from a write response",async()=>{ const raw=JSON.stringify({tool_name:"mcp__binance_agentic__tool_execute",tool_input:{toolName:"spot.newOrder",arguments:{symbol:"BNBUSDT",side:"BUY",type:"MARKET",quoteOrderQty:10}},tool_response:{content:[{type:"text",text:'{"symbol":"BNBUSDT","orderId":987654,"status":"FILLED"}'}],isError:false},tool_use_id:"executed-write"}); await postToolUse(raw,repoRoot,environment); const entries=parseReceiptLines(await readFile(path.join(home,"receipts.jsonl"),"utf8")); expect(entries[0]).toMatchObject({kind:"execution",toolUseId:"executed-write",orderId:"987654",isError:false}); });
});
